import React, { useState, useEffect } from 'react';
import axios from 'axios';

// WeeklyReportsPage.js
// Route: /reports
// Shows AI-generated weekly Tamil + English district reports
// Backend: /api/reports/{district} GET, /api/reports/generate POST (see backend patch)

const API_BASE = process.env.REACT_APP_BACKEND_URL || '';

const DISTRICTS = [
  'Chennai','Coimbatore','Madurai','Tiruchirappalli','Salem','Tirunelveli',
  'Vellore','Erode','Thoothukudi','Dindigul','Thanjavur','Ranipet',
  'Sivaganga','Virudhunagar','Namakkal','Kanchipuram','Karur','Krishnagiri',
  'Nagapattinam','Nilgiris','Perambalur','Pudukkottai','Ramanathapuram',
  'Tirupattur','Tiruppur','Tiruvallur','Tiruvannamalai','Tiruvarur',
  'Villupuram','Kallakurichi','Chengalpattu','Tenkasi','Mayiladuthurai',
  'Cuddalore','Ariyalur','Dharmapuri','Kanyakumari',
];

const WeeklyReportsPage = () => {
  const [district, setDistrict] = useState('Chennai');
  const [reports, setReports] = useState([]);
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(false);
  const [lang, setLang] = useState('ta');
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => { fetchReports(district); }, [district]);

  const fetchReports = async (d) => {
    setLoading(true);
    try {
      const res = await axios.get(`${API_BASE}/api/reports/${encodeURIComponent(d)}`);
      const data = res.data.reports || [];
      setReports(data);
      if (data.length > 0) setSelected(data[0]);
      else setSelected(null);
    } catch { setReports([]); setSelected(null); }
    setLoading(false);
  };

  const generateNow = async () => {
    setGenerating(true);
    try {
      await axios.post(
        `${API_BASE}/api/reports/generate`,
        { district },
        { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }
      );
      await fetchReports(district);
    } catch (e) { alert('Generation failed — try again'); }
    setGenerating(false);
  };

  const copyShareText = () => {
    if (!selected) return;
    const text = `📊 ${district} மாவட்ட வாராந்திர அறிக்கை\n${selected.week_label}\n\n${selected.summary_en?.substring(0,200)}...\n\nமேலும் படிக்க: ${window.location.origin}/reports`;
    navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2500); });
  };

  const printReport = () => {
    if (!selected) return;
    const win = window.open('', '_blank');
    win.document.write(`<!DOCTYPE html><html><head><title>${district} - ${selected.week_label}</title>
    <style>
      body{font-family:Arial,sans-serif;padding:40px;max-width:700px;margin:0 auto;color:#111}
      h1{color:#B91C1C;font-size:22px} h2{color:#374151;border-bottom:1px solid #e5e7eb;padding-bottom:8px;font-size:16px}
      .stats{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}
      .stat{padding:10px 16px;background:#f3f4f6;border-radius:8px;text-align:center}
      .stat span{display:block} .stat .n{font-size:22px;font-weight:800} .stat .l{font-size:11px;color:#6b7280}
      .tamil{font-size:15px;line-height:2;color:#111} p{line-height:1.7}
      .issue{padding:10px 0;border-bottom:1px solid #f3f4f6}
      .footer{margin-top:40px;font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:16px}
    </style></head><body>
    <h1>மக்கள் குரல் — Makkal Kural</h1>
    <p style="color:#6b7280;font-size:13px">${district} District Weekly Report — ${selected.week_label}</p>
    <div class="stats">
      <div class="stat"><span class="n">${selected.stats?.total_issues||0}</span><span class="l">Issues</span></div>
      <div class="stat"><span class="n">${selected.stats?.resolved||0}</span><span class="l">Resolved</span></div>
      <div class="stat"><span class="n">${selected.stats?.serious||0}</span><span class="l">Serious</span></div>
      <div class="stat"><span class="n">${selected.stats?.votes||0}</span><span class="l">Votes</span></div>
    </div>
    <h2>தமிழ் சுருக்கம்</h2>
    <p class="tamil">${selected.summary_ta||'Not available'}</p>
    <h2>English Summary</h2>
    <p>${selected.summary_en||'Not available'}</p>
    <h2>Top Issues</h2>
    ${(selected.top_issues||[]).map((iss,i)=>`<div class="issue"><strong>${i+1}. ${iss.category} — ${iss.local_body_name||''}</strong><br><small>${iss.description?.substring(0,150)||''}</small></div>`).join('')}
    <div class="footer">Generated by Makkal Kural · ${window.location.origin} · ${new Date().toLocaleDateString('en-IN')}</div>
    </body></html>`);
    win.document.close(); win.print();
  };

  return (
    <div style={S.page}>
      <div style={S.container}>
        <div style={S.header}>
          <div>
            <h1 style={S.title}>📰 Weekly District Reports</h1>
            <p style={S.subtitle}>AI-generated Tamil & English summaries — every Monday automatically</p>
          </div>
          <div style={S.langRow}>
            {['ta','en'].map(l => (
              <button key={l} onClick={() => setLang(l)} style={{
                ...S.langBtn,
                backgroundColor: lang===l ? '#B91C1C' : 'transparent',
                color: lang===l ? '#fff' : '#6b7280',
              }}>{l==='ta' ? 'தமிழ்' : 'EN'}</button>
            ))}
          </div>
        </div>

        <div style={S.controls}>
          <select value={district} onChange={e => setDistrict(e.target.value)} style={S.select}>
            {DISTRICTS.map(d => <option key={d}>{d}</option>)}
          </select>
          <button onClick={generateNow} disabled={generating} style={S.genBtn}>
            {generating ? '⏳ Generating...' : '✨ Generate Now'}
          </button>
          {selected && (
            <>
              <button onClick={copyShareText} style={S.actionBtn}>{copied ? '✓ Copied!' : '📤 Share'}</button>
              <button onClick={printReport} style={S.actionBtn}>🖨️ Print</button>
            </>
          )}
        </div>

        {loading ? <div style={S.empty}>Loading...</div> : reports.length === 0 ? (
          <div style={S.empty}>
            <div style={{fontSize:40,marginBottom:12}}>📭</div>
            <div style={{fontSize:16,fontWeight:700,color:'#374151'}}>No reports yet for {district}</div>
            <div style={{fontSize:13,color:'#9ca3af',marginTop:6}}>Reports generate every Monday. Click "Generate Now" to create the first one.</div>
          </div>
        ) : (
          <div style={S.layout}>

            {/* Sidebar list */}
            <div style={S.sidebar}>
              <div style={S.sidebarTitle}>Past Reports</div>
              {reports.map((r,i) => (
                <div key={i} onClick={() => setSelected(r)} style={{
                  ...S.reportItem,
                  borderColor: selected?.id===r.id ? '#B91C1C' : '#e5e7eb',
                  backgroundColor: selected?.id===r.id ? '#fff7f7' : '#fff',
                }}>
                  <div style={{fontSize:13,fontWeight:700,color:'#111827'}}>{r.week_label}</div>
                  <div style={{fontSize:11,color:'#6b7280',marginTop:2}}>{r.stats?.total_issues||0} issues · {r.stats?.resolved||0} resolved</div>
                  <span style={{
                    fontSize:10,fontWeight:700,padding:'2px 8px',borderRadius:20,display:'inline-block',marginTop:4,
                    backgroundColor: r.sentiment==='critical' ? '#fee2e2' : r.sentiment==='improving' ? '#dcfce7' : '#fef9c3',
                    color: r.sentiment==='critical' ? '#dc2626' : r.sentiment==='improving' ? '#16a34a' : '#ca8a04',
                  }}>
                    {r.sentiment==='critical' ? '🔴 Critical' : r.sentiment==='improving' ? '🟢 Improving' : '🟡 Stable'}
                  </span>
                </div>
              ))}
            </div>

            {/* Report detail */}
            {selected && (
              <div style={S.detail}>
                <div style={{fontSize:18,fontWeight:800,color:'#111827',marginBottom:4}}>{district} — {selected.week_label}</div>
                <div style={{fontSize:12,color:'#9ca3af',marginBottom:16}}>Generated: {new Date(selected.generated_at).toLocaleDateString('en-IN')}</div>

                {/* Stats */}
                <div style={S.statsGrid}>
                  {[
                    {icon:'📋',val:selected.stats?.total_issues||0,label:'Issues'},
                    {icon:'✅',val:selected.stats?.resolved||0,label:'Resolved'},
                    {icon:'🚨',val:selected.stats?.serious||0,label:'Serious'},
                    {icon:'👥',val:selected.stats?.votes||0,label:'Votes'},
                    {icon:'📈',val:`${selected.stats?.total_issues>0?Math.round((selected.stats.resolved/selected.stats.total_issues)*100):0}%`,label:'Rate'},
                    {icon:'🔺',val:selected.stats?.escalated||0,label:'Escalated'},
                  ].map(s => (
                    <div key={s.label} style={S.statCard}>
                      <span style={{fontSize:18}}>{s.icon}</span>
                      <span style={{fontSize:20,fontWeight:800,color:'#111827'}}>{s.val}</span>
                      <span style={{fontSize:10,color:'#9ca3af'}}>{s.label}</span>
                    </div>
                  ))}
                </div>

                {/* Summary */}
                <div style={S.summaryBox}>
                  <div style={S.summaryLabel}>{lang==='ta' ? '📝 தமிழ் சுருக்கம்' : '📝 English Summary'}</div>
                  <div style={S.summaryText}>
                    {lang==='ta' ? (selected.summary_ta||'Tamil summary not available') : (selected.summary_en||'English summary not available')}
                  </div>
                </div>

                {/* Top issues */}
                {selected.top_issues?.length > 0 && (
                  <div style={{marginBottom:20}}>
                    <div style={S.secTitle}>🔥 Top Issues This Week</div>
                    {selected.top_issues.map((issue,i) => (
                      <div key={i} style={S.issueRow}>
                        <div style={S.rank}>{i+1}</div>
                        <div style={{flex:1}}>
                          <div style={{fontSize:14,fontWeight:600,color:'#111827'}}>{issue.category} — {issue.local_body_name||issue.ward||''}</div>
                          <div style={{fontSize:12,color:'#6b7280',marginTop:2}}>{issue.description?.substring(0,120)}...</div>
                        </div>
                        <div style={{fontSize:13,fontWeight:700,color:'#B91C1C',flexShrink:0}}>{issue.support_count} 👍</div>
                      </div>
                    ))}
                  </div>
                )}

                {/* Category bar chart */}
                {selected.category_breakdown && Object.keys(selected.category_breakdown).length > 0 && (
                  <div>
                    <div style={S.secTitle}>📊 Issues by Category</div>
                    {Object.entries(selected.category_breakdown).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([cat,count]) => (
                      <div key={cat} style={{display:'flex',alignItems:'center',gap:10,marginBottom:8}}>
                        <div style={{fontSize:12,color:'#374151',width:120,flexShrink:0}}>{cat}</div>
                        <div style={{flex:1,height:8,backgroundColor:'#f3f4f6',borderRadius:99,overflow:'hidden'}}>
                          <div style={{height:'100%',backgroundColor:'#B91C1C',borderRadius:99,width:`${Math.min(100,(count/(selected.stats?.total_issues||1))*100)}%`}} />
                        </div>
                        <div style={{fontSize:12,fontWeight:700,color:'#374151',width:28,textAlign:'right'}}>{count}</div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

const S = {
  page:{minHeight:'100vh',backgroundColor:'#f9fafb',padding:'24px 16px'},
  container:{maxWidth:960,margin:'0 auto'},
  header:{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:20,flexWrap:'wrap',gap:12},
  title:{fontSize:26,fontWeight:800,color:'#111827',margin:0},
  subtitle:{fontSize:14,color:'#6b7280',marginTop:4},
  langRow:{display:'flex',border:'1px solid #e5e7eb',borderRadius:8,overflow:'hidden'},
  langBtn:{padding:'7px 16px',border:'none',cursor:'pointer',fontSize:13,fontWeight:700,transition:'all 0.15s'},
  controls:{display:'flex',gap:8,marginBottom:20,flexWrap:'wrap'},
  select:{padding:'10px 14px',fontSize:14,fontWeight:600,border:'1px solid #e5e7eb',borderRadius:8,backgroundColor:'#fff',cursor:'pointer',flex:1,minWidth:160},
  genBtn:{padding:'10px 16px',fontSize:13,fontWeight:700,backgroundColor:'#B91C1C',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',flexShrink:0},
  actionBtn:{padding:'10px 14px',fontSize:13,fontWeight:700,backgroundColor:'#f3f4f6',color:'#374151',border:'1px solid #e5e7eb',borderRadius:8,cursor:'pointer',flexShrink:0},
  empty:{textAlign:'center',padding:60,color:'#9ca3af'},
  layout:{display:'grid',gridTemplateColumns:'200px 1fr',gap:14},
  sidebar:{backgroundColor:'#fff',border:'1px solid #e5e7eb',borderRadius:12,padding:14,height:'fit-content'},
  sidebarTitle:{fontSize:11,fontWeight:700,color:'#9ca3af',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:10},
  reportItem:{padding:'10px 12px',borderRadius:8,border:'1px solid',marginBottom:6,cursor:'pointer',transition:'all 0.15s'},
  detail:{backgroundColor:'#fff',border:'1px solid #e5e7eb',borderRadius:12,padding:20},
  statsGrid:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginBottom:20},
  statCard:{display:'flex',flexDirection:'column',alignItems:'center',padding:'12px 8px',backgroundColor:'#f9fafb',borderRadius:10,gap:3},
  summaryBox:{marginBottom:20,padding:16,backgroundColor:'#fafafa',borderRadius:10,border:'1px solid #f3f4f6'},
  summaryLabel:{fontSize:13,fontWeight:700,color:'#374151',marginBottom:10},
  summaryText:{fontSize:14,color:'#374151',lineHeight:1.9},
  secTitle:{fontSize:12,fontWeight:700,color:'#6b7280',textTransform:'uppercase',letterSpacing:'0.04em',marginBottom:12},
  issueRow:{display:'flex',alignItems:'flex-start',gap:10,padding:'10px 0',borderBottom:'1px solid #f3f4f6'},
  rank:{width:26,height:26,backgroundColor:'#B91C1C',color:'#fff',borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:800,flexShrink:0},
};

export default WeeklyReportsPage;
